language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq  -y && sudo apt-get -qq -y install build-essential pkg-config $BOOST_PKG libcrypto++-dev libsqlite3-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install boost pkg-config && brew cleanup; fi
  - .jenkins.d/10-ndn-cxx.sh
install: 
  - .jenkins.d/20-ndn-cxx.sh


branches:
  only:
    - master



os:
  - linux
  # - osx

osx_image: xcode61
